[phases.setup]
nixpkgs = ['python3', 'pip']

[build]
image = 'python'
command = "pip install -r requirements.txt"  # Instalar dependências do projeto

[phases.run]
command = "python -m flask --app app run --host=0.0.0.0 --port=5000"  # Rodar a aplicação Flask

[env]
FLASK_APP = "app.py"
