[phases.setup]
nixpkgs = ['python311Full']

[phases.install]
cmds = [
  "python3 -m ensurepip",                  # Garante que o pip seja instalado
  "python3 -m pip install --upgrade pip",  # Atualiza pip
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn vectorize_pdf_railway:app --host=0.0.0.0 --port=5000"
