[phases.setup]
nixpkgs = ['python3', 'pip']

[build]
image = 'python'
command = "pip install -r requirements.txt"  # Instalar as dependências listadas no requirements.txt

[phases.run]
command = "python -m flask run --host=0.0.0.0 --port=5000"  # Rodar o Flask diretamente com o Python
