[phases.setup]
nixpkgs = ['python3', 'pip']

[build]
image = 'python'
command = "pip install -r requirements.txt"  # Instalar dependências do projeto

[phases.run]
command = command = "pip install -r requirements.txt"

[phases.run]
command = "uvicorn main:app --host=0.0.0.0 --port=5000"
