[phases.setup]
nixpkgs = ['python311Full']

[phases.install]
cmds = [
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.start]
cmd = "/opt/venv/bin/uvicorn vectorize_pdf:app --host=0.0.0.0 --port=$PORT"
