[phases.setup]
nixpkgs = ['python3', 'pip']

[build]
image = 'python'
command = "pip install -r requirements.txt"  # Instalar as dependências do projeto

[phases.run]
command = "uvicorn vectorize_pdf_railway:app --host=0.0.0.0 --port=8000 --reload"
