[phases.setup]
nixpkgs = ['python311Full']

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn vectorize_pdf:app --host=0.0.0.0 --port=$PORT"
